---
title: "Moja pierwsza prezentacja"
author: "Agata Zywert"
date: "16 marca 2018"
output: ioslides_presentation
---
# Czemu warto umieć się bić?

## Oto różne argumenty:

- Można się obronić będąc napadniętym przez złoczyńców
- Można przywalić komuś jak gada głupoty
- Ludzie się wtedy ciebie boją
- Bicie się robi ładne bicepsy
- Można sobie podnieść samoocenę
- Można wyładować zbędną agresję

## Jakie są minusy bicia się?
> Ogólnie moim zdaniem to są minusy do zaakceptowania, które w ogóle nie powinny przeważać w decyzji o tym, czy nauczyć się bić:

- robią się siniaki
- jeśli jesteś dziewczyną, chłopaki będą do ciebie mówić "stary" albo "ziomek"

# Chciałabym umieć zmienić kolor i font i w ogóle 
zrobić coś więcej, ale chyba jestem na to troszkę za durna narazie, więc może chociaż **zrobię** _to_ **_hehe_**

# Mam takie poczucie
- że powinnam zająć się w życiu czynś _sensownym_, bo ostatnio to tylko siedzę przed kompem, biję ludzi i biegam nad morze. Cytując klasyka:
> "I don’t understand how people… live. It’s amazing to me that people wake up every morning and say: ‘Yeah, another day, let’s do it.’ How do people do it? I don’t know how."

# Okazało się, że umiem jeszcze zrobić tak `print(fajnie_co)` że niby to jest code, **SO MUCH FUN**

## Dziękuję za obecność na mojej prezentacji o _niczym_

- jak
- mam
- żyć
